services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
    ports:
      - "8090:8080"
      - "11470:11470"
      - "12470:12470"
    volumes:
      - "stremio_data:/root/.stremio-server"

volumes:
  stremio_data:
