name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '25 10 * * *'
  push:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64, linux/arm64/v8
        tags: ghcr.io/tsaridas/stremio-docker:nightly
