name: DockerHub-Release

on:
  repository_dispatch:
    types: [new-release]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
      
    - name: Build & Publish Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/arm/v6,linux/amd64,linux/arm64/v8,linux/arm/v7
        tags: stremio/server:${{ github.event.client_payload.tag }}, tsaridas/stremio-docker:latest
        build-args: BRANCH=refactor/video-player
        cache-from: type=gha
        cache-to: type=gha,mode=max
